// <auto-generated />
using System;
using Lab5_Gadgets.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab5_Gadgets.Migrations
{
    [DbContext(typeof(GadgetContext))]
    partial class GadgetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Lab5_Gadgets.Models.SalesRep", b =>
                {
                    b.Property<int>("salesRepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("salesRepExt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salesRepFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salesRepLName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("salesRepID");

                    b.ToTable("salesRep");
                });

            modelBuilder.Entity("Lab5_Gadgets.Models.appointment", b =>
                {
                    b.Property<int>("appointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("appointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("customerID")
                        .HasColumnType("int");

                    b.Property<string>("salesRepFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salesRepID")
                        .HasColumnType("int");

                    b.Property<string>("salesRepLName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("appointmentID");

                    b.HasIndex("customerID");

                    b.HasIndex("salesRepID");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("Lab5_Gadgets.Models.customer", b =>
                {
                    b.Property<int>("customerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("customerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerLName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerPhonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerID");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("Lab5_Gadgets.Models.appointment", b =>
                {
                    b.HasOne("Lab5_Gadgets.Models.customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab5_Gadgets.Models.SalesRep", "salesRep")
                        .WithMany()
                        .HasForeignKey("salesRepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("salesRep");
                });
#pragma warning restore 612, 618
        }
    }
}
